'\" t
.TH FTVIEW 1 "December 2014" "Freetype 2.5.5"
.
.
.SH NAME
.
ftbench \- benchmark some common FreeType paths
.
.
.SH SYNOPSIS
.
.B ftbench
.RI [ options ]
.I fontname
.
.
.SH DESCRIPTION
.
The
.B ftbench
tool measures performance of some common FreeType operations.
.
.PP
This program is part of the FreeType demos package.
.
.
.SH OPTIONS
.
.TP
.B \-C
Compare with cached version if available.
.
.TP
.BI \-c \ n
Use at most
.I n
iterations for each test (0 means time limited).
.
.TP
.BI \-f \ l
Use hexadecimal number
.I l
as load flags (see
.RB ` FT_LOAD_XXX '
macros in the FreeType reference).
.
.TP
.B \-H
Use alternative hinting engine (Adobe CFF or TTF v35).
.
.TP
.BI \-i \ idx
Start with index
.I idx
(default is 0).
.
.TP
.BI \-m \ m
Set maximum cache size to
.I M
KiByte (default is 1024).
.
.TP
.B \-p
Preload font file in memory.
.
.TP
.BI \-r \ n
Set render mode to
.IR n :
.
.RS
.TS
tab (@);
rB l.
0@normal
1@light
2@mono
3@horizontal LCD
4@verical LCD
.TE
.RE
.
.IP
(default is 0).
.
.TP
.BI \-s \ s
Use
.I s
ppem as face size (default is 10ppem).
If set to zero, don't call
.BR FT_Set_Pixel_Sizes .
Use value\ 0 with option
.RB ` "-f\ 1" '
or something similar to load the glyphs unscaled,
otherwise errors will show up.
.
.TP
.BI \-t \ t
Use at most
.I t
seconds per test (default is 2).
.
.TP
.BI \-b \ tests
Perform chosen tests:
.
.RS
.TS
tab (@);
rB l.
a@load a glyph (FT_Load_Glyph)
b@load advance widths (FT_Get_Advances)
c@render a glyph (FT_Render_Glyph)
d@load a glyph (FT_Get_Glyph)
e@get glyph cbox (FT_Glyph_Get_CBox)
f@get glyph indices (FT_Get_Char_Index)
g@iterate CMap (FT_Get_{First,Next}_Char)
h@open a new face (FT_New_Face)
i@embolden (FT_GlyphSlot_Embolden)
j@get glyph bbox (FT_Outline_Get_BBox)
.TE
.RE
.
.IP
(default is
.BR abcdefghij ,
this is, all tests).
.
.TP
.B \-v
Show version.
.
.\" eof
