.TH FTGAMMA 1 "December 2014" "FreeType 2.5.5"
.
.
.SH NAME
.
ftgamma \- screen gamma calibration helper
.
.
.SH SYNOPSIS
.
.B ftgamma
.
.
.SH DESCRIPTION
.
The
.B ftgamma
demo program opens a window showing vertical grey bars, where the grey
in the upper half is shown as real color while the grey in the bottom
half is a 50%/50% mixture of black and white pixels.
Your monitor's gamma value roughly corresponds to the bar where the upper
and the lower half are equally bright if seen from some distance.
.
.PP
This program does not have any options.
Pressing any key closes the window again.
.
.PP
This program is part of the FreeType demos package.
.
.\" eof
